[master_node]
controlplane ansible_host=192.168.104.57
[workers]
node01 ansible_host=192.168.104.54
node02 ansible_host=192.168.104.53
node03 ansible_host=192.168.104.55
[k8s_cluster:children]
master_node
workers
[k8s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519